export const GENRE_OPTIONS = [
  "Accion",
  "Aventura",
  "Animacion",
  "Ciencia ficcion",
  "Comedia",
  "Crimen",
  "Documental",
  "Drama",
  "Fantasia",
  "Misterio",
  "Romance",
  "Terror",
  "Thriller",
] as const;
